### ISSUE TITLE
OSSサプライチェーンはサプライチェーン

### ISSUE THREAD

**Issue by fu7mu4** [OpenChain-Project/Onboarding-JWG#1]
リーフレットに「OSSサプライチェーン」とありますが、正しくは「サプライチェーン」ではないでしょうか。
というのもOpenChainでのサプライチェーンは「OSS」を含んでいなくても正しく機能することを目指しているからです。これはつまり「OSS」を含んでいないことを正しく扱えるという意味です。

**Comment by yuji-nomura** [comment]
コメントありがとうございます。確かに「OSSサプライチェーン」だと適切では無いですね。仕様書では「ソフトウェア　サプライチェーン」という表現も使われていますが単に「サプライチェーン」という表記にしてみます。
