### ISSUE TITLE
Markdown or some text base format

### ISSUE THREAD

**Issue by fu7mu4** [OpenChain-Project/Onboarding-JWG#13]
This repositry has documents in binary format (ex. docx,pptx). 
It is not best way to collaborate with various environment/OS

1. Editting them on macOS or Linux may break displayed style cause of missing font.
2. Cannot receive pull request from other.

I suggest text base format like a Markdown for this project.

現在、PowerPointなどの形式のファイルで作成されていますが次の問題があります。
- macOSやLinux上で編集した場合、Fontなどのために表示が乱れます。
- バイナリフォーマットであるため他からのプルリクエストなどができません。
そのため、Markdownなどのテキストベースのフォーマットで議論し、リリース時にPowerPointなどの形式に変換することを提案します。

**Comment by nori0428** [comment]
I pretty much agree with you.But I think there's a issue below.

-  We will sometimes make discussions that require diagrams and flow charts. In such a case, in the markdown format, we have to use tools such as 'mermaid.js' etc. which makes handling difficult.

So, I think it's good to do the discussion on github issues(here) as the format of the document can be anything.

How is it?

---

私もほぼ同意見ではありますが、一点、問題があると思っています。
- 図やフローチャートといったものを含んだ資料で議論することがあり、その場合は、markdownなどテキストベースでは取り扱いが難しくなる場合があると思います。

そのため、ドキュメント自体はフォーマットを縛らず、github issues(ここ)で議論を行う、勿論、markdownで資料が上がっている場合にはsendPRする、という形をとるのはいかがでしょうか?

**Comment by hfukuchi** [comment]
どの資料に関するご意見でしょうか。課題は認識しておりますが、Markdownで対応できるものと、対応できないものとあるかもしれません。

Business Flow図に関して言いますと、確定したものが無いためブレーンストーミングレベルにあり、皆さんに頭の中でイメージしたものを図にしています。そこからアイディアを集約・まとめようとしています。このレベルでMarkdownで図を作成するのは難しいかもしれません。
これから役割を抽出していく予定ですが、そのリストはMarkdownで作成して、議論する予定です。

**Comment by hfukuchi** [comment]
本件の提案を受けて、新しいレポート（Business workflowとRolesを分析したもの）は、Markdownで記述しています。

https://github.com/OpenChain-Project/Onboarding-JWG/blob/master/CaseStudy/BusinessFlow/Report-of-business-workflow-and-roles.md

**Comment by hfukuchi** [comment]
Please share it. 
(But, I am still writing it.)
