### ISSUE TITLE
We have two versions of the one page leaflet - WHY? (just kidding)

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Onboarding-JWG#2]
There are two versions of the document but Git has native version control so I suggest deleting one:

a_openchain_leaflet_20180615.pptx
a_openchain_leaflet_20180629.pptx

**Comment by shanecoughlan** [comment]
Not sure who is in charge of this so no @name reference. Sorry.

**Comment by hfukuchi** [comment]
Nomura-san manages the leaflet. I assigned Nomura-san and Imada-san.

**Comment by nobuoimada** [comment]
Moved the older versions into sub dirs and changed the file name of current versions.
