### ISSUE TITLE
We need to have a license file for this repo

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Onboarding-JWG#3]
Over to the JP WG Team! Do your magic.

**Comment by hfukuchi** [comment]
License for contribution and report to OpenChain activity
1. report 
1-1. case study with a company name : licensed under CC-BY-ND-4.0
anonymous report : licensed under CC0-1.0
1-2. picture : licensed under CC-BY-ND-4.0

2. contribution to Japan WG
licensed under CC0-1.0
meeting memo, comment to specification, introduction document, leaflet, general explanation of case study, case study format

1.　OpenChainプロジェクトへの報告（Report）については以下に従う
1-1.　各社から報告された社名入りのケーススタディ: ライセンスをCC-BY-ND-4.0 とする
名前、著作権を表記
ただし、匿名の報告は、CC0-1.0とする
1-2.　写真: ライセンスをCC-BY-ND-4.0とする
2.　プロジェクトへの貢献（Contribution）については以下に従う
ライセンスをCC0-1.0とする（OpenChain Projectと同じ運用）
議事録、仕様へのコメント、JWG紹介資料、リーフレット、Lightning Talkの説明資料やフォーマット

**Comment by hfukuchi** [comment]
LICENSEファイル追加の提案 #4
https://github.com/OpenChain-Project/Onboarding-JWG/pull/4
でLICENSEファイルが追加されたので、本件はクローズします。
