### ISSUE TITLE
We need to have an explanation about Japan Work Group

### ISSUE THREAD

**Issue by hfukuchi** [OpenChain-Project/Onboarding-JWG#6]
We need to have an explanation about Japan Work Group, and relationship between OpenChain project and Japan Work Group.
The explanation is useful for newcomers to read and understand Japan Work Group at the first place.

**Comment by shanecoughlan** [comment]
Here is my suggestion:

The OpenChain Project is a collaborative project hosted at the Linux Foundation. It is organized according to a project charter with:
1 - A Governing Board made up from Platinum Members
2 - Steering and Outreach Committees with voting members from the Platinum Members, the Work Team leads and community representatives
3 - Work Teams (Specification, Curriculum, Conformance and Outreach) for wide community engagement and discussion

The OpenChain Japan Work Group is a country-specific part of the OpenChain community. It is intended to share information with the international work teams to:
a - Make it easier to understand and adopt OpenChain
b - Support Japanese companies in their compliance activities

**Comment by hfukuchi** [comment]
説明資料を登録するPull Requestがマージされました。

今後は、以下の資料をメンテしてください。
https://github.com/OpenChain-Project/Onboarding-JWG/blob/master/About_Japan-wg/About_JapanWG.md
